---
- name: "Add Docker Repository GPG key"
  apt_key: url="https://download.docker.com/linux/ubuntu/gpg" id="9DC858229FC7DD38854AE2D88D81803C0EBFCD88" state="present"

- name: "Add Docker Repository"
  apt_repository: repo="deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"

- name: "Install Docker-ce"
  apt: name="docker-ce" state="present"
