- name: "Create Apt configuration directory"
  file: path="/etc/apt.conf.d" state=directory

- name: "Setup APT Proxy"
  template: src="apt-proxy.conf.j2" dest="/etc/apt.conf.d/99-proxy"

- name: "Copy Environment file"
  tempate: src="environment.j2" dest="/etc/environment"
