---
- name: Upgrade All packages
  apt: name="*" state="latest" force_apt_get=True

- name: Install Development Packages
  apt: name="build-essential" state="present"

- name: Reboot System
  reboot:
  when: reboot

- name: "Install handy tools"
  apt: name="{{ packages }}" state=present
  vars:
    packages:
    - htop
    - nload
    - iotop
    - iftop
    - traceroute
    - telnet
    - mtr
    - apt-transport-https
    - ca-certificates
    - software-properties-common
